name: imgenc_frontend
description: Secure Steganography App Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  file_selector: ^1.1.0
  image: ^4.7.2
  encrypt: ^5.0.3
  crypto: ^3.0.7
  file_picker: ^10.3.8
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true
